### ISSUE TITLE
[Suggestion] Tweak to prevent torchlight from disabling spawners

### ISSUE THREAD

**Issue by Luke616** [Pyrofab/SpawnerControl#2]
Title, have been looking for a mod which does this for a while and have not been able to find one. Here's why I think it would be a beneficial change for some packs:

- Prevents cheese from Astral Sorcery cave illuminator and torch arrows in roguelike dungeons
- Makes dungeons with active spawners more dangerous, encouraging players to break them
- Makes it harder to set up mob farms as mobs would be constantly spawning

A caveat to this tweak is that it would be nice if sunlight did disable spawning, or else an open-sky spawner would be free, infinite mob loot for skeletons or zombies,

Thank you for your consideration!
Luke616

**Comment by Pyrofab** [comment]
Due to the way the spawn check works, if I disable the light check, it will disable every mob-specific spawn check. I can reimplement some of them, but not all. Would that be acceptable ?

**Comment by Luke616** [comment]
That would work better actually, it would give more flexibility to pack/map makers who want to put spawners for nether only mobs in the overworld, for example. Am I understanding that right? It would only be for mob spawner blocks correct?

**Comment by Pyrofab** [comment]
Indeed, it would only be for mob spawners. Also the case you mentioned already works in vanilla, it's more about things like strays and husks spawning in caves or slimes spawning only in swamps and slime chunks.

**Comment by Pyrofab** [comment]
Added in 1.4, feedback is welcome

**Comment by Luke616** [comment]
Thanks! Working great for me, really glad to have this feature for my pack
