### ISSUE TITLE
Mob spawn counter not incrementing with custom spawners' mobs.

### ISSUE THREAD

**Issue by Insane-96** [Pyrofab/SpawnerControl#3]
Mod Version: 1.6
Forge: 14.23.3.2668
![2018-05-25_15 05 53](https://user-images.githubusercontent.com/7185104/40546153-b1e4cde6-602e-11e8-8749-c85bff421af5.png)
![2018-05-25_15 05 54](https://user-images.githubusercontent.com/7185104/40546154-b20d6a1c-602e-11e8-83e0-53a41aa825b7.png)

**Comment by Pyrofab** [comment]
I kind of want to blame Minecraft's weird spawning code for that one but I guess I should have read a bit more carefully. Anyway, fixed and waiting for curse approval.
